### ISSUE TITLE
Explore and test framework

### ISSUE THREAD

**Issue by ydaponte** [microsoft/data-factory-testing-framework#22]
**Goal**: Get acquainted with the framework, test it and provide feedback.

**Success criteria:** 
- Test the framework with the examples provided in the repo.
- Get acquainted with the code
- Provide feedback (document it in the issue) and create issues to address items

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azure-data-factory-testing-framework/issues/23
- [ ] https://github.com/microsoft/azure-data-factory-testing-framework/issues/24
- [ ] https://github.com/microsoft/azure-data-factory-testing-framework/issues/25
- [ ] https://github.com/microsoft/azure-data-factory-testing-framework/issues/27
- [ ] https://github.com/microsoft/data-factory-testing-framework/issues/41
- [ ] https://github.com/microsoft/data-factory-testing-framework/issues/42
```
