### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by ydaponte** [microsoft/data-factory-testing-framework#37]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/data-factory-testing-framework/issues/36
- [ ] https://github.com/microsoft/data-factory-testing-framework/issues/26
- [ ] https://github.com/microsoft/data-factory-testing-framework/issues/43
- [ ] https://github.com/microsoft/data-factory-testing-framework/issues/44
```

**Comment by ydaponte** [comment]
@jayachithra, can you please detail which aspects of the docs you wanted to address on this issue? Reason is we have several stories for improving the docs and we are trying to organize them better. Thanks in advance!
